# This workflow will run tests using node and then publish a package to GitHub Packages when a tag is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Build and deploy release

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
          - name: Install Nodejs
            uses: actions/setup-node@v1
            with:
              node-version: 15.x
          - name: Install dependencies
            uses: borales/actions-yarn@v2.0.0
            with:
              cmd: install
          - name: Build artifact
            uses: borales/actions-yarn@v2.0.0
            with:
              cmd: build --prod --build-optimizer --optimization
          - name: Deploy
            uses: burnett01/rsync-deployments@4.1
            with:
              switches: -avzr --delete
              path: dist/
              remote_path: /var/www/pleagan-service/
              remote_host: pleagan.vg
              remote_user: pleagan
              remote_key: ${{ secrets.PLEAGAN_DEPLOY_KEY }}
